### ISSUE TITLE
Error: Cannot find module './config/config.json'

### ISSUE THREAD

**Issue by dkregor** [Scopique/sadi#3]
I get the above error when I attempt to run this. Can you provide any guidance on what the config.json file should look like (warning... I'm a new to node.js and discord dev) or what I'm doing wrong.

**Comment by dkregor** [comment]
I'll also point out that there are a lot of process.env variables that can't be referenced. Any help with this would be greatly appreciated.

**Comment by Scopique** [comment]
Hmmm. I didn't realize this repo was public! But since it is, I have updated the readme with info on config and .env.

Config only sets the command prefix. .env contains the Discord and SCAPI client keys (which you'll need to get) and SCAPI endpoints for each data library that the bot uses. 

https://discord.com/developers/applications
https://starcitizen-api.com/
